language: node_js
node_js:
 - "node"

cache: npm

script: 
  - npm run test:unit

after_success:
  - npm run build

branches:
  only:
    - staging

# deploy:
#  provider: pages
#  skip_cleanup: true
# #  github_token: $GITHUB_TOKEN
#  local_dir: dist
#  on:
#   branch: staging