language: python

python:
  - "3.8"

addons:
  # install browsers
  firefox: latest

before_script:
  - cd ./backend/
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test
