# Generated by Django 3.1.7 on 2021-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_shipposition_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
