# Generated by Django 3.1.7 on 2021-04-21 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_auto_20210419_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipposition',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 15, 40, 4, 223562, tzinfo=utc), unique=True),
        ),
    ]
