# Generated by Django 3.1.7 on 2021-04-22 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_auto_20210421_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipposition',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 8, 43, 24, 323084, tzinfo=utc), unique=True),
        ),
    ]
