# Generated by Django 3.1.7 on 2021-04-22 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_auto_20210422_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipposition',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 9, 54, 29, 604290, tzinfo=utc), unique=True),
        ),
    ]
