# Generated by Django 3.1.7 on 2021-04-22 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_auto_20210422_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipposition',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
    ]
