# Generated by Django 3.1.7 on 2021-04-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_auto_20210422_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
