# Generated by Django 3.1.7 on 2021-05-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_mission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
