# Generated by Django 3.1.7 on 2021-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0011_timeline_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='color',
            field=models.CharField(default='#B6885D', max_length=8, null=True),
        ),
    ]
