# Generated by Django 3.1.7 on 2021-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_auto_20210504_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='color',
            field=models.CharField(default='#B6885D', max_length=7, null=True),
        ),
    ]
