# Generated by Django 3.1.7 on 2021-03-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
