# Generated by Django 3.1.7 on 2021-04-06 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionuser',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='missionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
