# Generated by Django 3.1.7 on 2021-04-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210406_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionuser',
            name='team_lab',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
