# Generated by Django 3.1.7 on 2021-04-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_shipposition_date_time'),
        ('users', '0004_auto_20210406_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='missions',
            field=models.ManyToManyField(through='users.MissionUser', to='missions.Mission'),
        ),
    ]
