# Generated by Django 3.1.7 on 2021-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_background_image',
            field=models.ImageField(default='profile.png', null=True, upload_to='profile_background_pics'),
        ),
    ]
