# Generated by Django 3.1.7 on 2021-04-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210415_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_background_image',
            field=models.ImageField(default='jakob-owens-turtle-unsplash.jpg', null=True, upload_to='profile_background_pics'),
        ),
    ]
