# Generated by Django 3.1.7 on 2021-04-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210416_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionuser',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='missionuser',
            name='job',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='missionuser',
            name='team_lab',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
