# Generated by Django 3.1.7 on 2021-04-27 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210427_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missionusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
