# Generated by Django 3.1.7 on 2021-04-27 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0008_auto_20210422_1156'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('details', models.TextField(blank=True, default='')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('color', models.CharField(default='#D33A3A', max_length=7, null=True)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduleuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
