# Generated by Django 3.1.7 on 2021-03-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_pics')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(0, 'Actu'), (1, 'Mediation'), (2, 'A_bord')])),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='missions.mission')),
            ],
        ),
    ]
