# Generated by Django 3.1.7 on 2021-03-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mission_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='users.missionuser'),
        ),
    ]
