# Generated by Django 3.1.7 on 2021-04-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_shipposition_date_time'),
        ('posts', '0002_post_mission_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='missions_pics')),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='missions.mission')),
            ],
        ),
    ]
