# Generated by Django 3.1.7 on 2021-04-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_shipposition_date_time'),
        ('posts', '0003_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Picture',
        ),
    ]
