# Generated by Django 3.1.7 on 2021-04-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_shipposition_date_time'),
        ('posts', '0004_auto_20210416_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
