# Generated by Django 3.1.7 on 2021-04-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210428_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Actu', 'Actu'), ('Med', 'Médiation'), ('Onboard', 'À bord')], max_length=20),
        ),
    ]
