# Generated by Django 3.1.7 on 2021-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210428_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='logo_triton.png', null=True, upload_to='post_pics'),
        ),
    ]
