# Generated by Django 3.1.7 on 2021-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210429_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='conque.png', null=True, upload_to='post_pics'),
        ),
    ]
